### PR TITLE
fix: Monitor/Fix out-of-memory bug when the bootstrapping is far behind

### LINKED ISSUE #153: Monitor: Running out of memory when bootstrapping from far behind
This issue is reported by @philmln. The root cause is that when the monitor bootstraps, it downloads a lot of BTC blocks from the BTC base height. It will naturally run out of memory when the monitor is far behind. @SebastianElvis and @vitsalis suggested that we follow an iterative approach to bootstrapping.

### PR DESCRIPTION
**Pull request by gitferry**
This PR fixed #153.

Previously, the bootstrapping downloaded all the BTC blocks from the base height to the latest height at once. This will cause an out-of-memory bug when the bootstrapping starts from far behind. This PR fixed this by downloading a single block each time and only proceeding to the next block after the previous block is done.

This PR doesn't use batching because there's no difference in doing it one by one

### CODE REVIEW

**Comment by SebastianElvis** [comment]
> This PR doesn't use batching because there's no difference in doing it one by one

The major difference between fetching one-by-one and fetching batch-by-batch is the total number of RPC queries. Sometimes RPC query is rather expensive and time-consuming so we'd be interested in reducing the number of RPC queries. By batching we could reduce the total number by `batch_size` times. Wdyt?

**Comment by gitferry** [comment]
@SebastianElvis I thought fetching block one-by-one and batch-by-batch all use the same PRC query `GetBlockByHash`. So they are essentially downloading BTC blocks one-by-one, aren't they?

**Comment by SebastianElvis** [comment]
Right, I see. So if btcd does not provide a native function for getting a range of block hashes, then this seems to be the best thing we can do.

**Comment by gitferry** [comment]
Yep. This procedure is kind of like we bootstrap a BTC full node which naturally takes time for security. To boost this procedure, the Babylon foundation could provide some sort of periodic checkpointing options so that the monitor can start from a much nearer height. But this introduces the Babylon foundation as a trusted third party.

File: monitor/btcscanner/btc_scanner.go [hunk 1]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
...
-
-	// replace all the unconfirmed blocks in the cache with new blocks to avoid forks
+	// clear all the blocks in the cache to avoid forks
 	bs.UnconfirmedBlockCache.RemoveAll()
-	err = bs.UnconfirmedBlockCache.Init(chainBlocks)
+
+	_, bestHeight, err := bs.BtcClient.GetBestBlock()
 	if err != nil {
-		panic(fmt.Errorf("failed to initialize BTC cache for tail blocks: %w", err))
+		panic(fmt.Errorf("can not get the best BTC block"))
```
Comment (SebastianElvis) [inline monitor/btcscanner/btc_scanner.go:142]:
```suggestion
		panic(fmt.Errorf("cannot get the best BTC block"))
```

File: monitor/btcscanner/btc_scanner.go [hunk 2]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
...
 	}
+	for ; firstUnconfirmedHeight <= bestHeight; firstUnconfirmedHeight++ {
```
Comment (SebastianElvis) [inline monitor/btcscanner/btc_scanner.go:144]: Do we need to refresh the best height for every iteration? Here `GetBlockByHeight` is a RPC query thus takes time. Maybe after a number of iterations the BTC blockchain grows and `bestHeight` increments.

In fact, L152 tries to trim confirmed blocks and gets trimmed blocks. This is already a check on whether `firstUnconfirmedHeight` reaches `bestHeight` or not. So maybe we could change L144 an infinite loop, and break at L154?

File: monitor/btcscanner/btc_scanner.go [hunk 3]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
 
 	log.Infof("the bootstrapping starts at %d", firstUnconfirmedHeight)
 
-	chainBlocks, err = bs.BtcClient.FindTailBlocksByHeight(firstUnconfirmedHeight)
```
Comment (SebastianElvis) [inline monitor/btcscanner/btc_scanner.go:136]: Now it looks like this function is very likely to cause memory issue. Maybe we should remove it?

**Review by SebastianElvis — APPROVED** [review]
That's a quick fix! 👏

File: monitor/btcscanner/btc_scanner.go (hunk 2 above)
Comment (vitsalis) [reply monitor/btcscanner/btc_scanner.go:144]: I guess we do not make this an infinite loop as this is a bootstrap method. Do we have safety that if the chain tip  increases while the bootstrap method is happening (which is very probable, given that we do `O(2N)` RPC queries for each BTC block) that we're not going to miss something?

File: monitor/btcscanner/btc_scanner.go [hunk 4]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
...
 	bs.UnconfirmedBlockCache.RemoveAll()
-	err = bs.UnconfirmedBlockCache.Init(chainBlocks)
+
+	_, bestHeight, err := bs.BtcClient.GetBestBlock()
 	if err != nil {
-		panic(fmt.Errorf("failed to initialize BTC cache for tail blocks: %w", err))
+		panic(fmt.Errorf("can not get the best BTC block"))
 	}
+	for ; firstUnconfirmedHeight <= bestHeight; firstUnconfirmedHeight++ {
+		ib, _, err := bs.BtcClient.GetBlockByHeight(firstUnconfirmedHeight)
```
Comment (vitsalis) [inline monitor/btcscanner/btc_scanner.go:145]: Why did we abandon the `GetBlockByHash` methodology? I think it is better as we do not need to do 2 RPC queries for each block, while it is also safer as there might be two bitcoin blocks on the same height.

File: monitor/btcscanner/btc_scanner.go [hunk 5]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
...
-	if err != nil {
-		panic(fmt.Errorf("failed to find the tail chain with base height %d: %w", bs.BaseHeight, err))
-	}
-
-	// replace all the unconfirmed blocks in the cache with new blocks to avoid forks
+	// clear all the blocks in the cache to avoid forks
 	bs.UnconfirmedBlockCache.RemoveAll()
-	err = bs.UnconfirmedBlockCache.Init(chainBlocks)
+
+	_, bestHeight, err := bs.BtcClient.GetBestBlock()
```
Comment (vitsalis) [inline monitor/btcscanner/btc_scanner.go:140]: I suggest we get the block that is `k+w` deep here (or at least `k` deep). By getting the tip of the chain it is probable that when we finish bootstrapping there might be a chain re-org. Or are we ok with this as we might catch it as an event (since we subscribe to BTC chain events before hand)? Also, could this issue appear in the reporter as well? @SebastianElvis

File: monitor/btcscanner/btc_scanner.go [hunk 6]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
...
 		}
-	}
 
-	bs.sendConfirmedBlocksToChan(confirmedBlocks)
-	log.Infof("bootstrapping is finished at the tip confirmed height: %d and tip unconfirmed height: %d", bs.confirmedTipBlock.Height, chainBlocks[len(chainBlocks)-1].Height)
+		// if the scanner was bootstrapped before, the new confirmed canonical chain must connect to the previous one
+		if bs.confirmedTipBlock != nil {
+			confirmedTipHash := bs.confirmedTipBlock.BlockHash()
+			if !confirmedTipHash.IsEqual(&confirmedBlocks[0].Header.PrevBlock) {
+				panic("invalid canonical chain")
```
Comment (vitsalis) [inline monitor/btcscanner/btc_scanner.go:161]: If we want to send an alert as a prometheus metric, maybe we don't panic here? This can be done on a future PR.

File: monitor/btcscanner/btc_scanner.go [hunk 7]
```diff
@@ -133,34 +134,38 @@ func (bs *BtcScanner) Bootstrap() {
...
-		return
-	}
+		bs.UnconfirmedBlockCache.Add(ib)
 
-	// if the scanner was bootstrapped before, the new confirmed canonical chain must connect to the previous one
-	if bs.confirmedTipBlock != nil {
-		confirmedTipHash := bs.confirmedTipBlock.BlockHash()
-		if !confirmedTipHash.IsEqual(&confirmedBlocks[0].Header.PrevBlock) {
-			panic("invalid canonical chain")
+		confirmedBlocks = bs.UnconfirmedBlockCache.TrimConfirmedBlocks(int(bs.K))
```
Comment (vitsalis) [inline monitor/btcscanner/btc_scanner.go:152]: Should we do this each time? The confirmed blocks always get appended by 1 block in each iteration. Further, won't the `confirmedBlocks` always be the `k-deep` block (i.e. `bs.UnconfirmedBlockCache[len(bs.UnconfirmedBlockCache)-k]`)?

**Review by vitsalis — APPROVED** [review]
Very good work! Some questions and suggestions about optimizing this.

File: monitor/btcscanner/btc_scanner.go (hunk 5 above)
Comment (SebastianElvis) [reply monitor/btcscanner/btc_scanner.go:140]: Yeah getting a `k`-deep chain seems to be the right option (not necessarily `k+w` since `w` captures the max time interval of censoring a tx in PoS chain). Getting the best block seems fine in reporter since reporter will handle block events later on anyway.

File: monitor/btcscanner/btc_scanner.go (hunk 2 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:144]: > Do we need to refresh the best height for every iteration? Here GetBlockByHeight is a RPC query thus takes time. Maybe after a number of iterations the BTC blockchain grows and bestHeight increments.

I think that would make this complex given the fact that BTC chain grows slowly. We also don't need to worry about missing new blocks during bootstrap. In this case, the bootstrap will be triggered again and will quickly catch up. See [here](https://github.com/babylonchain/vigilante/blob/b30f74a51e54851e42d0878639c8713317cf29f8/monitor/btcscanner/block_handler.go#L29).

> In fact, L152 tries to trim confirmed blocks and gets trimmed blocks. This is already a check on whether firstUnconfirmedHeight reaches bestHeight or not. So maybe we could change L144 to an infinite loop, and break at L154?

We don't want to break at L154 because we also want to add the rest blocks in our cache.

File: monitor/btcscanner/btc_scanner.go (hunk 3 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:136]: Very much agreed. But this is now used by the reporter. So probably will leave it to a future PR.

File: monitor/btcscanner/btc_scanner.go (hunk 4 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:145]: If we use `GetBlockByHash`, we would reversely iterate BTC chain to get the block we want. That would cause a lot of RPC queries.

Your concern is valid. To make sure it's safe, we need to add another check about whether the obtained block is on the same branch as the previous blocks in the cache. Will add this check later

File: monitor/btcscanner/btc_scanner.go (hunk 5 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:140]: If we cut `k` blocks, then every time we receive a new block, we need to fetch previous `k` blocks and pop a confirmed one. I don't think we need to worry about this because when we receive a new block, we need to make sure that it follows the same chain as those in the cache. If there's anything wrong, we clear the cache (unconfirmed blocks) and restart the bootstrapping.

File: monitor/btcscanner/btc_scanner.go (hunk 6 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:161]: Definitely. Thanks for the reminder

File: monitor/btcscanner/btc_scanner.go (hunk 7 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:152]: I think we do because we don't want to cache those blocks. Every time we download a new block we want to process it immediately (see the rest of the for loop) and only start to process the next when the previous one is done.

File: monitor/btcscanner/btc_scanner.go (hunk 5 above)
Comment (vitsalis) [reply monitor/btcscanner/btc_scanner.go:140]: I suggest we only cut those during bootstrapping, since it is a long process. Then, we would only need to do this for the first block that we receive, right?

File: monitor/btcscanner/btc_scanner.go (hunk 4 above)
Comment (vitsalis) [reply monitor/btcscanner/btc_scanner.go:145]: But here we are iterating the BTC chain in sequence eitherway, so the hash is readily available. Instead of 2 RPC queries we would do 1, no?

Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:145]: Right. The `GetBlockByHeight` first queries the block hash by height, then we call `GetBlockByHash`. So we do use 2 RPC queries.

File: monitor/btcscanner/btc_scanner.go (hunk 5 above)
Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:140]: Yep, we can do that. Not much difference in efficiency wise but indeed cleaner. Thanks!

Comment (gitferry) [reply monitor/btcscanner/btc_scanner.go:140]: After a second thought, I don't think requesting unconfirmed blocks when we receive the first block is a good idea because it is unknown that the received block is on the same branch as previously confirmed blocks. That would involve a bunch of checks and unnecessary PRC calls.
